Feature: new visualization plugin
EyeSeeTea/dashboard-reports pull request #15
Opened 2024-12-13 21:17 UTC by MatiasArriola

### :pushpin: References

-   **Issue:** https://app.clickup.com/t/8696vv89u #8696vv89u

### :memo: Implementation

- I went full circle on this one. First I removed every reference to the .js plugins usage (which I called "Legacy"), but then realized some visualizations won't work with its replacement (the iframes), and finally kept both implementations.
- Now the Legacy Plugin scripts are loaded dynamically only if required
- Created a separate `PluginVisualizationRepository`, and each  `get` is performed individually instead of batching all the requests at the repo level.
- According to DHIS docs, `eventCharts` and `eventReports` are being unified into `eventVisualizations`, so that one is used now.
- This is just the support for the new plugins but I left some placeholders to filter by OrgUnit.

### :fire: Testing

- Use any DHIS 39+ instance with some dashboards loaded to test.
- Older instances can be tested as well and should be supported using only legacy plugin
- I had intermittent issues during my tests, I still have to understand what happened. It may be related to the DHIS instances I used during testing, but mentioning just in case:
  - Inside the Map Visualizations, a form appeared instead of the map.
  - The iframes stopped reporting installationStatus correctly
  - Timeout errors in the postRobot communication, some loading indefinitely

2024-12-16 16:57 UTC, eperedo requested changes
Thanks @MatiasArriola! It looks good, just a few minor changes in the code.

I was able to load almost every visualization but not this dashboard with eventReport (I understand we should use the legacy plugin for this one, right?)

https://play.im.dhis2.org/stable-2-41-2/dhis-web-dashboard/#/GNlS3sXJZFE

![image](https://github.com/user-attachments/assets/2ea0847f-13b6-4667-9f25-cb0aa64d5a75)

![image](https://github.com/user-attachments/assets/12c8c255-0a16-470c-a083-5ded75251ae3)

2024-12-16 16:57 UTC, eperedo commented on src/webapp/hooks/useLegacyVisualizationPlugin.ts
> +                    throw new Error(`Legacy plugin "${dashboardItem.legacyReportType}" not found`);
Let's use `i18n.t` for any message displayed in the UI.

2024-12-16 18:52 UTC, MatiasArriola commented
Thanks @eperedo !

I've implemented the corrections and I will keep them in mind for future changes.

Regarding that particular dashboard, I believe I missed it because it wasn't there past week, and also most of my testing was done against the 2-40-6 instance.
The Item is not loading because when we make the metadata GET request to build the dashboard, the `eventVisualization` field is not included in the response in that  dashboardItem. As a result, the item is filtered out.
Here is a working example of a dashboard that uses event charts and event reports: https://play.im.dhis2.org/stable-2-41-2/dhis-web-dashboard/#/eZSIccgeq94. For these dashboardItems, the `eventVisualization` field is returned. 

I don't understand why that dashboard doesn't return the `eventVisualization` field in the item, while others do. 
I've stopped using the `eventReports` entity to align with the [docs recommendations](https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-241/visualizations.html#webapi_event_visualization). 

If needed for legacy support, we could add back the `eventChart` and `eventReport` to the metadata GET fields requested.

2024-12-17 16:08 UTC, eperedo approved these changes
Thanks @MatiasArriola, looks good to me. 

You're right about the `eventVisualization` I've tested in the test environment of the client that is working with the app and visualizations include the eventVisualization object. So let's keep your implementation.

2024-12-18 16:12 UTC, merged