feat: Add Org Units filter
EyeSeeTea/dashboard-reports pull request #16
Opened 2024-12-30 12:49 UTC by MatiasArriola

### :pushpin: References

-   **Issue:** https://app.clickup.com/t/8696vv89u #8696vv89u

### :memo: Implementation

- Added Organization Units Filter for visualizations
  - Using a `TextField` and a `ConfirmationDialog`, similar to `user-extended-app` filter implementation
- Upgraded `@eyeseetea/*` and `@dhis/*` dependencies 

### :art: Screenshots

![image](https://github.com/user-attachments/assets/d2b857b1-ce9c-4b15-b03b-54060e01d134)

2025-01-06 19:42 UTC, eperedo requested changes
Thanks @MatiasArriola, looks good, just some minor observations. Let me know if you have any questions

2025-01-06 19:42 UTC, eperedo commented on src/webapp/components/org-units-filter/OrgUnitPicker.tsx
> +            onChildrenLoaded={{}}
[No need to change anything here]
Having an empty object for a prop is weird, but I just realized we need this in the latest version of ui-components. Leaving this comment here as a reminder to validate [the prop here](https://github.com/EyeSeeTea/d2-ui-components/blob/development/src/org-unit-tree/OrgUnitTree.component.js#L93) and avoid passing an empty object.

2025-01-06 19:42 UTC, eperedo commented on src/webapp/hooks/useOrgUnitRoots.ts
> +    const [orgUnitRootIds, setOrgUnitRootIds] = React.useState<string[] | undefined>();
`Id` instead `string` to be more explicit

2025-01-06 19:42 UTC, eperedo commented on src/webapp/hooks/useOrgUnitRoots.ts
> +                    snackbar.openSnackbar("error", err);
No need to change, but we also have the error method: `snackbar.error(err)`

2025-01-07 12:41 UTC, MatiasArriola commented on src/webapp/components/org-units-filter/OrgUnitPicker.tsx
> +            onChildrenLoaded={{}}
Good catch. I forgot to comment on that, but I was required to provide an empty object, otherwise the OrgUnitSelector throws an undefined Error

2025-01-07 13:40 UTC, MatiasArriola commented
Thanks @eperedo! I've implemented the changes. As we discussed privately, I've kept the `orgUnitIds`. Anything else, let me know

2025-01-07 16:47 UTC, eperedo approved these changes
All good, thanks @MatiasArriola

2025-01-07 16:47 UTC, merged